[phases.setup]
nixPkgs = ["nodejs_20", "chromium"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node dist/server/entry.mjs"

[variables]
NODE_ENV = "production"
HOST = "0.0.0.0"
PORT = "3000"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/*-chromium-*/bin/chromium"
