#!/bin/bash

# Script to translate remaining 12 pages to English and Chinese
# This script will be used as a reference for manual translation

echo "🌍 Translating remaining 12 pages..."
echo ""
echo "Pages to translate:"
echo "1. FAQ (EN + CN)"
echo "2. Downloads (EN + CN)"
echo "3. Privacy Policy (EN + CN)"
echo "4. Terms of Service (EN + CN)"
echo "5. Cookie Policy (EN + CN)"
echo "6. 404 Page (EN + CN)"
echo ""
echo "Total: 12 pages"
echo ""
echo "⚠️  Note: These pages exist but contain Vietnamese content"
echo "📝 Action: Replace Vietnamese content with proper translations"
echo ""
echo "Files to update:"
echo "  - src/pages/en/faq.astro"
echo "  - src/pages/en/downloads.astro"
echo "  - src/pages/en/privacy-policy.astro"
echo "  - src/pages/en/terms-of-service.astro"
echo "  - src/pages/en/cookie-policy.astro"
echo "  - src/pages/en/404.astro"
echo "  - src/pages/cn/faq.astro"
echo "  - src/pages/cn/downloads.astro"
echo "  - src/pages/cn/privacy-policy.astro"
echo "  - src/pages/cn/terms-of-service.astro"
echo "  - src/pages/cn/cookie-policy.astro"
echo "  - src/pages/cn/404.astro"
echo ""
echo "✅ Ready to translate!"
